<?php

namespace Schuh\BlogBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends DocumentRepository
{
    public function findNArticlesByPage($n, $p)
    {
        return $this->findBy(array(), array('published', 'desc'), $n, $p);
    }
}