<?php

namespace Schuh\BlogBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends DocumentRepository
{
    /**
     * Retrieves Articles for a pager
     * 
     * @param type $params
     * @param int $n number of Articles per page
     * @param int $p number of the page
     * @return array the Article objects
     */
    public function findNArticlesByPage($params, $n, $p)
    {
        return $this->findBy($params, array('published' => 'desc'), $n, $n * ($p - 1));
        
//        return $this->createQueryBuilder()
//            ->limit($n)
//            ->skip($n * ($p - 1))
//            ->sort('published', 'desc')
//            ->getQuery()
//            ->execute();
    }
 
    /**
     * Retrieves Articles by slug
     * 
     * @param string $slug 
     * @param type $params
     * @param int $n number of Articles per page
     * @param int $p number of the page
     * @return array the Article objects
     */
    public function findByCategorySlug($slug, $params)
    {
        $result = array();
        //$articles = $this->findNArticlesByPage($params, $n, $p);
        $articles = $this->findBy($params);
        
        foreach ($articles as $article) {
            if ($article->getCategory()->getSlug() === $slug) {
                $result[] = $article;
            }
        }

        return $result;
    }
}