generator: admingenerator.generator.doctrine_odm
params:
  model: Schuh\BlogBundle\Document\Article
  namespace_prefix: Schuh
  bundle_name: BlogAdminBundle
  fields: ~

builders:
  list:
    params:
      title: Liste des articles
      display: [ title, author, created, updated, published ]
      fields:
        title: { label: Titre }
        author: { label: Auteur }
        created: { label: Création }
        updated: { label: Mise-à-jour }
        published: { label: Publication }
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: Nouvel article
      display: ~
      actions:
        list: ~
  edit:
    params:
      title: Edition de "{{ YourModel.title }}"
      display: [ title, text ]
      actions:
        list: ~
  delete: ~
