generator: admingenerator.generator.doctrine_odm
params:
  model: Schuh\BlogBundle\Document\Article
  namespace_prefix: Schuh
  bundle_name: BlogAdminBundle
  fields: ~

builders:
  list:
    params:
      title: List for BlogAdminBundle
      display: ~
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: New object for BlogAdminBundle
      display: ~
      actions:
        list: ~
  edit:
    params:
      title: You're editing the object "{{ YourModel.title }}"
      display: ~
      actions:
        list: ~
  delete: ~
